# Generated by Django 5.1 on 2024-09-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantConsent',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('respiratory_conditions', models.CharField(blank=True, max_length=255, null=True)),
                ('cardiovascular_conditions', models.CharField(blank=True, max_length=255, null=True)),
                ('cardiovascular_symptoms', models.CharField(blank=True, max_length=255, null=True)),
                ('metabolic_conditions', models.CharField(blank=True, max_length=255, null=True)),
                ('mental_health_conditions', models.CharField(blank=True, max_length=255, null=True)),
                ('stress_level', models.CharField(max_length=50)),
                ('lifestyle_factors', models.CharField(blank=True, max_length=255, null=True)),
                ('sleep_hours', models.CharField(max_length=50)),
                ('sleep_disorders', models.CharField(blank=True, max_length=255, null=True)),
                ('last_medical_checkup', models.CharField(max_length=50)),
                ('health_concerns', models.CharField(blank=True, max_length=255, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
